# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: psicopdg_dev


test:
  <<: *default
  database: psicopdg_test


production:
  <<: *default
  database: psicopdg_prod
